### ISSUE TITLE
thellier_magic IndexError

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#474]
**What command was run:**

```
thellier_magic.py -fmt png -sav -spc mgk09t1PI01 -WD data_files/3_0/Megiddo
```
**What happened:**

```
Traceback (most recent call last):
  File "/Users/nebula/anaconda3/bin/thellier_magic.py", line 11, in <module>
    sys.exit(main())
  File "/Users/nebula/Python/PmagPy/programs/thellier_magic.py", line 350, in main
    mpars = pmag.domean(araiblock[1], start, end, 'DE-BFL')
  File "/Users/nebula/Python/PmagPy/pmagpy/pmag.py", line 2637, in domean
    if indata[end0] != datablock[end]:
IndexError: list index out of range
```

**Details:**

It looks like the problem is happening because the zijdblock is 1 record longer then the length of the araiblock:

zijdblock:

```
[[273.0, 147.7, -10.3, 5.95e-07, 1, 'g', ''], 
[373.0, 152.0, -11.8, 5.82e-07, 1, 'g', ''], 
[473.0, 149.4, -13.4, 5.04e-07, 0, 'g', ''], 
[523.0, 151.3, -12.6, 4.56e-07, 1, 'g', ''], 
[573.0, 151.8, -14.4, 4.06e-07, 0, 'g', ''], 
[623.0, 152.7, -12.9, 3.64e-07, 1, 'g', ''], 
[673.0, 152.0, -16.0, 3.24e-07, 0, 'g', ''], 
[713.0, 152.5, -13.2, 2.8300000000000003e-07, 1, 'g', ''], 
[753.0, 154.6, -18.6, 2.27e-07, 0, 'g', ''], 
[793.0, 155.6, -14.6, 1.42e-07, 1, 'g', ''], 
[833.0, 155.4, -37.3, 7.07e-08, 0, 'g', ''], 
[853.0, 155.3, -19.0, 3.32e-08, 1, 'g', '']]
```

araiblock[1]:
```
[[273, 0.0, 0.0, 0.0, 1], 
[373.0, 68.63377428448868, -59.22267721106515, 4.127562804313254e-08, 1], 
[473.0, 198.50011051041784, -82.74549798271947, 1.0958615901173566e-07, 0], 
[523.0, 33.4553132464908, -86.3155534262901, 1.62260031258414e-07, 1], 
[573.0, 245.21968750087905, -87.57972106750883, 2.2765719962266611e-07, 0], 
[673.0, 240.7316932895032, -88.43103935436223, 3.578104141247124e-07, 0], 
[713.0, 276.613467892653, -87.50322207930644, 4.1150989333257583e-07, 1], 
[753.0, 252.23477204029467, -89.13141857845704, 4.977136836564665e-07, 0], 
[793.0, 327.9054246380596, -88.47165073401189, 6.469080611411464e-07, 1], 
[833.0, 340.1570877405032, -88.94436500940107, 8.052797049739216e-07, 0], 
[853.0, 309.86855672668867, -88.60432901593839, 8.66314572943106e-07, 1]]
```

This means that `end` is set to 11, which causes the error in `domean`.

```
for plotrec in zijdblock:
                if plotrec[0] == beg_int:
                    start = recnum  # while we are at it, collect these bounds                                                           
                if plotrec[0] == end_int:
                    end = recnum
...
                mpars = pmag.domean(araiblock[1], start, end, 'DE-BFL')
```

How should we fix this error, or is this a problem with the data file?

**Data file(s):**

In PmagPy/data_files/3_0/Megiddo

**Comment by moonshoes87** [comment]
I think that might be because it isn’t getting to the problem specimen:

In ipmag.thellier_magic:

    specimens = specimens[0:5]  # just plot the first 5

Is that line a mistake?

**Comment by ltauxe** [comment]
oh.  oops.  yeah that shouldn’t be in there.  
i’ll take a look.

**Comment by ltauxe** [comment]
I fixed both the limit on specimens (shouldn't have been there in the first place) and the failure to plot specimens with no data.

**Comment by moonshoes87** [comment]
@ltauxe, do you want me to implement the various options that are available in the command line version of thellier_magic.py into ipmag.thellier_magic?

**Comment by ltauxe** [comment]
sure that would be great!  thanks
lisa

**Comment by moonshoes87** [comment]
it looks like the IndexError is not fully resolved:

See:
```
ipmag.thellier_magic(input_dir_path='data_files/convert_2_magic/livdb_magic/TH_IZZI+')
```
@ltauxe, can you look at this?  Otherwise I think the implementation of ipmag.thellier_magic is working well, and it is now being used in thellier_magic.py.

**Comment by moonshoes87** [comment]
This works now.
